#!usr/bin/ruby

fastlane_version "2.0"

default_platform :ios

platform :ios do

    desc 'Deploy a build for beta testing'
    lane :internal do
        match(type: 'appstore')

        build_number = ENV['BITRISE_BUILD_NUMBER']
        increment_build_number(
            build_number: build_number
        )

        gym(
            export_method: 'app-store',
            configuration: 'Internal'
        )

        pilot(
            beta_app_description: 'Build for an internal testing purpose',
            skip_waiting_for_build_processing: true,
            skip_submission: true,
            itc_provider: "X86NQK83T7"
        )
    end
end
